param()
$ErrorActionPreference='Stop'
$v2=[IO.Path]::GetFullPath((Join-Path $PSScriptRoot '..\..'))
$root=Join-Path ([IO.Path]::GetTempPath()) ('orcivo-deepseek-tests-'+[guid]::NewGuid().ToString('N'))
$results=New-Object System.Collections.Generic.List[object]
function Check([string]$Id,[scriptblock]$Body){try{& $Body;$results.Add("$Id PASS")}catch{$results.Add("$Id FAIL: $($_.Exception.Message)")}}
function Assert-True($Value,[string]$Message){if(-not $Value){throw $Message}}
function Write-TestJson([string]$Path,$Value){New-Item -ItemType Directory -Force -Path (Split-Path -Parent $Path)|Out-Null;[IO.File]::WriteAllText($Path,($Value|ConvertTo-Json -Depth 20),(New-Object Text.UTF8Encoding($false)))}
try{
    . (Join-Path $v2 'lib-v2.ps1');. (Join-Path $v2 'classify.ps1');. (Join-Path $v2 'real-agent.ps1');. (Join-Path $v2 'dispatcher.ps1')
    New-Item -ItemType Directory -Force -Path $root|Out-Null;$runtime=Join-Path $root 'provider-runtime.v1.json';$script:DeepSeekRuntimePath=$runtime;$script:DeepSeekBudgetDir=Join-Path $root 'budgets';$registry=Join-Path $root 'deepseek-price-registry.v1.json';Copy-Item (Join-Path $v2 'deepseek-price-registry.v1.json') $registry;$script:DeepSeekPriceRegistryPath=$registry
    $manifest=Read-V2Json $registry
    $cfg=[ordered]@{schemaVersion='orcivo.orchestration.v2.provider-runtime/1';enabled=$true;enabledProviders=@('deepseek','codex');excludedProviders=@('claude');budgets=[ordered]@{monthlyDeepSeekBudgetUsd=5};deepseek=[ordered]@{baseUrl='https://api.deepseek.com/';wireApi='responses';envKey='DEEPSEEK_API_KEY';codexHomeRoot='orcivo-dispatcher/providers/deepseek-codex';profiles=[ordered]@{FAST=[ordered]@{model='deepseek-v4-flash';reasoning='low';maxEstimatedUsd=0.03};BALANCED=[ordered]@{model='deepseek-v4-pro';reasoning='high';maxEstimatedUsd=0.20};REASONING=[ordered]@{model='deepseek-v4-pro';reasoning='high';maxEstimatedUsd=0.20}};pricing=[ordered]@{status='VERIFIED';manifestHash=[string]$manifest.manifestHash}};codex=[ordered]@{profiles=[ordered]@{CRITICAL=[ordered]@{model='gpt-5.6-terra';reasoning='high'}}}}
    Write-TestJson $runtime $cfg
    Check 'DS-01' {Assert-True ((Get-DeepSeekModelPlan FAST).model -eq 'deepseek-v4-flash') 'LOW did not select Flash';Assert-True ((Get-DeepSeekModelPlan BALANCED).reasoning -eq 'high') 'NORMAL did not select Pro/high'}
    Check 'DS-02' {foreach($case in @(@(401,'TEMPORARY_AUTH_FAILURE'),@(402,'QUOTA_EXHAUSTED'),@(429,'RATE_LIMIT'),@(500,'PROVIDER_UNAVAILABLE'),@(503,'PROVIDER_UNAVAILABLE'))){$control=[ordered]@{isError=$true;httpStatus=$case[0];errorType='http';message='provider response'};$legacy=Get-FailureClassV2 -Provider deepseek -ExitCode 1 -Control $control;$canonical=ConvertTo-CanonicalFailureClass $legacy $control;Assert-True ($canonical -eq $case[1]) "HTTP $($case[0]) classified $canonical"}}
    Check 'DS-03' {$legacy=Get-FailureClassV2 -Provider deepseek -ExitCode 0 -Control $null;Assert-True ($legacy -eq 'INCOMPLETE_PROVIDER_RESULT') 'exit zero without terminal event became success';$timeout=ConvertTo-CanonicalFailureClass (Get-FailureClassV2 -Provider deepseek -ExitCode 124 -Control $null) $null;Assert-True ($timeout -eq 'TRANSIENT_PROVIDER_NETWORK') 'timeout was not temporary transport'}
    Check 'DS-04' {$homeBefore=$env:CODEX_HOME;$launch=Get-DeepSeekLaunchConfiguration -Model deepseek-v4-flash -Reasoning low -MaxOutputTokens 1024;Assert-True ($launch.codexHome -match 'orcivo-dispatcher[\\/]providers[\\/]deepseek-codex$') 'CODEX_HOME is not isolated';Assert-True ($env:CODEX_HOME -eq $homeBefore) 'DeepSeek mutated parent Codex Plus home';Assert-True (($launch.configArgs -join ' ') -match 'wire_api') 'Responses wire API missing';Assert-True (($launch.configArgs -join ' ') -match 'model_providers\.deepseek\.name') 'DeepSeek provider name is missing';Assert-True (($launch.configArgs -join ' ') -match 'model_max_output_tokens=1024') 'output limit is missing'}
    Check 'DS-05' {$entry=Register-DeepSeekUsage -Usage ([ordered]@{inputTokens=1000;outputTokens=1000;cachedTokens=100}) -InvocationId ('att-'+('a'*32)) -Model deepseek-v4-flash -ReturnedModels @('DeepSeek-V4-Flash-0731') -ResultClass SUCCESS -ExitCode 0;Assert-True ([decimal]$entry.costUsd -gt 0) 'usage cost was not recorded';$status=Get-DeepSeekBudgetStatus;Assert-True ($status.spentUsd -gt 0 -and $status.remainingUsd -lt 5) 'durable budget did not decrease'}
    Check 'DS-06' {$cfg.deepseek.pricing.status='UNCONFIGURED';Write-TestJson $runtime $cfg;$status=Get-DeepSeekBudgetStatus;Assert-True (-not $status.ok -and $status.reason -match 'bound') 'unverified price table did not fail closed';$cfg.deepseek.pricing.status='VERIFIED';Write-TestJson $runtime $cfg}
    Check 'DS-07' {$events=@([pscustomobject]@{type='response.completed';response=[pscustomobject]@{model='DeepSeek-V4-Flash-0731';usage=[pscustomobject]@{input_tokens=3;output_tokens=2;cached_tokens=1}}});Assert-True (Test-DeepSeekFinalStructuredEvent $events) 'final Responses event was rejected';$usage=Get-DeepSeekUsageFromEvents $events;Assert-True ($usage.inputTokens -eq 3 -and $usage.cachedTokens -eq 1) 'usage/cache telemetry parse failed';Assert-True (Test-DeepSeekReturnedModel -RequestedModel deepseek-v4-flash -ReturnedModels (Get-DeepSeekReturnedModel $events)) 'resolved returned model was rejected'}
    Check 'DS-08' {$plan=Get-OrcivoCodexModelPlan CRITICAL;Assert-True ($plan.ok -and $plan.model -eq 'gpt-5.6-terra' -and $plan.reasoning -eq 'high') 'HIGH did not pin Codex Plus Terra/high'}
    Check 'DS-09' {Assert-True ((Get-DeepSeekPricingPeriod ([datetime]'2026-09-07T01:00:00Z')) -eq 'PEAK') 'peak start failed';Assert-True ((Get-DeepSeekPricingPeriod ([datetime]'2026-09-07T04:00:00Z')) -eq 'OFF_PEAK') 'peak end failed';Assert-True ((Get-DeepSeekPricingPeriod ([datetime]'2026-09-12T06:30:00Z')) -eq 'OFF_PEAK') 'weekend must be off-peak'}
    Check 'DS-10' {$hit=Register-DeepSeekUsage -Usage ([ordered]@{inputTokens=100;outputTokens=100;cachedTokens=100}) -InvocationId ('att-'+('b'*32)) -Model deepseek-v4-pro -ReturnedModels @('DeepSeek-V4-Pro-0813') -ResultClass SUCCESS -ExitCode 0;$miss=Register-DeepSeekUsage -Usage ([ordered]@{inputTokens=100;outputTokens=100;cachedTokens=0}) -InvocationId ('att-'+('c'*32)) -Model deepseek-v4-pro -ReturnedModels @('DeepSeek-V4-Pro-0813') -ResultClass SUCCESS -ExitCode 0;Assert-True ([decimal]$hit.costUsd -lt [decimal]$miss.costUsd) 'cache hit was not priced separately'}
    Check 'DS-11' {try{Register-DeepSeekUsage -Usage ([ordered]@{inputTokens=1;outputTokens=1;cachedTokens=0}) -InvocationId ('att-'+('d'*32)) -Model deepseek-v4-flash -ReturnedModels @('wrong') -ResultClass SUCCESS -ExitCode 0;throw 'model mismatch accepted'}catch{Assert-True ($_.Exception.Message -match 'returned model') 'wrong model failure reason'}}
    Check 'DS-12' {$bad=Read-V2Json $registry;$bad.models.'deepseek-v4-flash'.PEAK.output=9;Write-TestJson $registry $bad;$p=Get-DeepSeekPriceManifest;Assert-True (-not $p.ok -and $p.reason -match 'hash') 'tampered registry was accepted';Copy-Item (Join-Path $v2 'deepseek-price-registry.v1.json') $registry -Force}
    Check 'DS-13' {$cfg.budgets.monthlyDeepSeekBudgetUsd=0.01;Write-TestJson $runtime $cfg;try{Assert-DeepSeekInvocationBudget -EstimatedUsd 0.03;throw 'insufficient budget accepted'}catch{Assert-True ($_.Exception.Message -match 'budget') 'insufficient budget failure missing'}}
    Check 'DS-14' {$cfg.budgets.monthlyDeepSeekBudgetUsd=5;Write-TestJson $runtime $cfg;Register-DeepSeekUnknownUsage -InvocationId ('att-'+('e'*32)) -Model deepseek-v4-flash -Reason 'usage is absent' -ResultClass AGENT_FAILURE -ExitCode 0|Out-Null;$record=Read-V2Json (Get-DeepSeekBudgetPath);$status=Get-DeepSeekBudgetStatus;Assert-True ($null -eq $record.invocations[-1].costUsd -and -not $status.ok -and $status.reason -match 'unknown cost') 'absent usage was priced as zero or did not block later paid calls'}
    Check 'DS-15' {$cfg.budgets.monthlyDeepSeekBudgetUsd=5;Write-TestJson $runtime $cfg;$mh='sha256:'+('f'*64);$m=New-DeepSeekRequestManifest -InvocationId ('att-'+('1'*32)) -PromptHash $mh -Model deepseek-v4-flash -Reasoning low -Profile FAST;$missing=@([pscustomobject]@{type='turn.completed';usage=[pscustomobject]@{input_tokens=10;output_tokens=2}});$r=Resolve-DeepSeekBillableModel -RequestManifest $m -Events $missing -ExitCode 0;Assert-True ($r.ok -and $r.billableModelSource -eq 'REQUEST_MANIFEST' -and -not $r.returnedModelObserved -and $r.period -eq 'PEAK') 'request-manifest upper-bound resolution was rejected';$present=@([pscustomobject]@{type='turn.completed';response=[pscustomobject]@{model='DeepSeek-V4-Flash-0731';usage=[pscustomobject]@{input_tokens=10;output_tokens=2}}});$exact=Resolve-DeepSeekBillableModel -RequestManifest $m -Events $present -ExitCode 0;Assert-True ($exact.ok -and $exact.billableModelSource -eq 'API_RESPONSE' -and $exact.returnedModelObserved) 'compatible returned model was rejected'}
    Check 'DS-16' {$m=New-DeepSeekRequestManifest -InvocationId ('att-'+('2'*32)) -PromptHash ('sha256:'+('e'*64)) -Model deepseek-v4-flash -Reasoning low -Profile FAST;$bad=_ToHashtable (($m|ConvertTo-Json -Depth 20)|ConvertFrom-Json);$bad.baseUrl='https://evil.invalid/';$signed=[ordered]@{};foreach($k in $bad.Keys){if($k -ne 'manifestHash'){$signed[$k]=$bad[$k]}};$bad.manifestHash=New-ContentHash $signed;Assert-True (-not(Test-DeepSeekRequestManifest $bad).ok) 'endpoint drift was accepted';$bad=_ToHashtable (($m|ConvertTo-Json -Depth 20)|ConvertFrom-Json);$bad.provider='codex';$signed=[ordered]@{};foreach($k in $bad.Keys){if($k -ne 'manifestHash'){$signed[$k]=$bad[$k]}};$bad.manifestHash=New-ContentHash $signed;Assert-True (-not(Test-DeepSeekRequestManifest $bad).ok) 'provider switch was accepted'}
    Check 'DS-17' {$m=New-DeepSeekRequestManifest -InvocationId ('att-'+('3'*32)) -PromptHash ('sha256:'+('d'*64)) -Model deepseek-v4-pro -Reasoning high -Profile REASONING;$wrong=@([pscustomobject]@{type='turn.completed';response=[pscustomobject]@{model='DeepSeek-V4-Flash-0731';usage=[pscustomobject]@{input_tokens=10;output_tokens=2}}});Assert-True (-not(Resolve-DeepSeekBillableModel -RequestManifest $m -Events $wrong -ExitCode 0).ok) 'returned model contradiction was accepted';Assert-True (-not(Resolve-DeepSeekBillableModel -RequestManifest $m -Events @([pscustomobject]@{type='turn.completed'}) -ExitCode 0).ok) 'absent usage was accepted'}
    Check 'DS-19' {$events=@([pscustomobject]@{type='item.completed';item=[pscustomobject]@{type='error';message='metadata warning'}},[pscustomobject]@{type='turn.completed';usage=[pscustomobject]@{input_tokens=12814;output_tokens=75}});$control=ConvertFrom-CodexEvents $events;Assert-True ($control -and -not $control.isError -and (Get-FailureClassV2 -Provider deepseek -ExitCode 0 -Control $control) -eq 'OK') 'real DeepSeek turn.completed stream was classified as incomplete'}
    Check 'DS-20' {$aggregate=@([pscustomobject]@{type='turn.completed';usage=[pscustomobject]@{input_tokens=12400984;output_tokens=59326;reasoning_output_tokens=16891}});$limit=Test-DeepSeekPerResponseOutputLimit -Events $aggregate -MaxOutputTokens 16000;Assert-True (-not $limit.exceeded) 'aggregate turn usage was incorrectly treated as a per-response cap violation';$single=@([pscustomobject]@{type='response.completed';response=[pscustomobject]@{usage=[pscustomobject]@{output_tokens=16001}}});Assert-True ((Test-DeepSeekPerResponseOutputLimit -Events $single -MaxOutputTokens 16000).exceeded) 'per-response cap violation was not detected'}
    Check 'DS-21' {
        $required='{"error":{"message":"Required properties must match all properties in the object","type":"invalid_request_error"}}';$variant='{"error":{"message":"Invalid json schema: field ''type'': unknown variant ''object'', expected one of ''string'', ''number'', ''integer'', ''boolean'', ''null''","type":"invalid_request_error"}}'
        $make={param($message)@([pscustomobject]@{type='error';message=$message},[pscustomobject]@{type='turn.failed';error=[pscustomobject]@{message=$message}})}
        $first=Get-DeepSeekStructuredOutputFailureDiagnostic -Events (&$make $required);$second=Get-DeepSeekStructuredOutputFailureDiagnostic -Events (&$make $variant)
        $unrelated=Get-DeepSeekStructuredOutputFailureDiagnostic -Events (&$make '{"error":{"message":"Invalid parameter: temperature","type":"invalid_request_error"}}');$auth=Get-DeepSeekStructuredOutputFailureDiagnostic -Events (&$make '{"error":{"message":"Authentication failed","type":"authentication_error"}}');$rate=Get-DeepSeekStructuredOutputFailureDiagnostic -Events (&$make '{"error":{"message":"Rate limit exceeded","type":"rate_limit_error"}}')
        Assert-True ($first.classification -eq 'AGENT_INFRASTRUCTURE' -and $first.code -eq 'STRICT_STRUCTURED_OUTPUT_SCHEMA_REJECTED' -and $second.classification -eq 'AGENT_INFRASTRUCTURE' -and $second.code -eq 'STRICT_STRUCTURED_OUTPUT_SCHEMA_REJECTED' -and $null -eq $unrelated -and $null -eq $auth -and $null -eq $rate) 'strict schema diagnostics were over- or under-classified'
    }
    Check 'DS-23' {$dir=Join-Path $root 'ds23';New-Item -ItemType Directory -Force -Path $dir|Out-Null;$prompt=Join-Path $dir 'reviewer-001-deepseek-77777777.prompt.txt';$stdout=Join-Path $dir 'reviewer-001-deepseek-77777777.stdout.log';$stderr=Join-Path $dir 'reviewer-001-deepseek-77777777.stderr.log';$raw='{"type":"error","message":"{\"error\":{\"message\":\"Required properties must match all properties in the object\",\"type\":\"invalid_request_error\"}}"}'+"`n"+'{"type":"turn.failed","error":{"message":"{\"error\":{\"message\":\"Required properties must match all properties in the object\",\"type\":\"invalid_request_error\"}}"}}'+"`n";[IO.File]::WriteAllText($prompt,'review',(New-Object Text.UTF8Encoding($false)));[IO.File]::WriteAllText($stdout,$raw,(New-Object Text.UTF8Encoding($false)));[IO.File]::WriteAllText($stderr,'',(New-Object Text.UTF8Encoding($false)));$result=ConvertTo-RealAgentInvocationResult -Provider deepseek -Role reviewer -InvocationId ('att-'+('7'*32)) -Attempt 1 -Profile FAST -Route ([ordered]@{model='deepseek-v4-flash';reasoningIntent='low';capabilityVersion='fixture';maxOutputTokens=1024}) -ExitCode 1 -DurationSec 1 -StdoutText $raw -PromptFile $prompt -StdoutLog $stdout -StderrLog $stderr;Assert-True ($result.providerClass -eq 'AGENT_INFRASTRUCTURE' -and $result.failureDiagnostic.code -eq 'STRICT_STRUCTURED_OUTPUT_SCHEMA_REJECTED') 'durable agent result collapsed strict schema rejection into generic provider unavailability'}
    Check 'DS-22' {
        $oldV2=$script:V2Dir;$oldCfg=$script:V2Config;$oldLedger=$script:LedgerDir;$oldBudget=$script:DeepSeekBudgetDir;$oldProbe=$script:DispatcherRecoveryRunnerProbe
        try{
            $tv=('b'*64);$run='run-ds22-fixture';$inv=('att-'+('5'*32));$localV2=Join-Path $root 'ds22-v2';New-Item -ItemType Directory -Force -Path $localV2|Out-Null;Copy-Item (Join-Path (Get-RepoRoot) '.orchestration\v2\config.v2.json') (Join-Path $localV2 'config.v2.json')
            $script:V2Dir=$localV2;$script:V2Config=Join-Path $localV2 'config.v2.json';$script:LedgerDir=Join-Path $localV2 'ledger';$script:DeepSeekBudgetDir=Join-Path $localV2 'budgets';$script:DispatcherRecoveryRunnerProbe=$false
            $logs=Join-Path $localV2 "runs\$run\logs";New-Item -ItemType Directory -Force -Path $logs|Out-Null;$stem='reviewer-002-deepseek-55555555';$prompt=Join-Path $logs ($stem+'.prompt.txt');[IO.File]::WriteAllText($prompt,'review prompt',(New-Object Text.UTF8Encoding($false)));$promptHash=New-FileHash $prompt
            $request=New-DeepSeekRequestManifest -InvocationId $inv -PromptHash $promptHash -Model deepseek-v4-flash -Reasoning low -Profile FAST;$requestPath=Join-Path $logs ($stem+'.request-manifest.json');Write-TestJson $requestPath $request
            $stdout=Join-Path $logs ($stem+'.stdout.log');$stderr=Join-Path $logs ($stem+'.stderr.log');$raw='{"type":"thread.started"}'+"`n"+'{"type":"error","message":"{\"error\":{\"message\":\"Invalid json schema: field ''type'': unknown variant ''object'', expected one of ''string'', ''number'', ''integer'', ''boolean'', ''null''\",\"type\":\"invalid_request_error\"}}"}'+"`n"+'{"type":"turn.failed","error":{"message":"{\"error\":{\"message\":\"Invalid json schema: field ''type'': unknown variant ''object'', expected one of ''string'', ''number'', ''integer'', ''boolean'', ''null''\",\"type\":\"invalid_request_error\"}}"}}'+"`n";[IO.File]::WriteAllText($stdout,$raw,(New-Object Text.UTF8Encoding($false)));[IO.File]::WriteAllText($stderr,'',(New-Object Text.UTF8Encoding($false)));$stdoutHash=New-FileHash $stdout;$stderrHash=New-FileHash $stderr
            $receipt=[ordered]@{schemaVersion='orcivo.orchestration.v2.agent-result-receipt/1';invocationId=$inv;provider='deepseek';model='deepseek-v4-flash';profile='FAST';reasoningIntent='low';attempt=2;exitCode=1;providerClass='PROVIDER_UNAVAILABLE';failureDiagnostic=$null;resultClass='AGENT_FAILURE';structuredResult=$null;promptArtifact=$prompt;promptHash=$promptHash;stdoutArtifact=$stdout;stdoutHash=$stdoutHash;stderrArtifact=$stderr;stderrHash=$stderrHash;controlRecordHash=$stdoutHash;duration=3;contextRolloverRequired=$false;capabilityVersion='fixture';continuationCheckpoint='';usage=$null;cachedTokens=$null;returnedModels=@();requestManifestPath=$requestPath;requestManifestHash=[string]$request.manifestHash;costUsd=$null;telemetryConsistent=$false;createdAt=(Get-Date).ToUniversalTime().ToString('o');receiptHash=''};$signed=[ordered]@{};foreach($k in $receipt.Keys){if($k -ne 'receiptHash'){$signed[$k]=$receipt[$k]}};$receipt.receiptHash=New-ContentHash $signed;$receiptPath=Join-Path $logs ($stem+'.agent-result.json');Write-TestJson $receiptPath $receipt
            $history=[ordered]@{invocationId=$inv;role='REVIEWER';provider='deepseek';model='deepseek-v4-flash';reasoningEffort='low';attempt=2;providerClass='PROVIDER_UNAVAILABLE';resultClass='AGENT_FAILURE';exitCode=1;stdoutArtifact=$stdout;stdoutHash=$stdoutHash;stderrArtifact=$stderr;stderrHash=$stderrHash;controlRecordHash=$stdoutHash;usage=$null;cachedTokens=$null;costUsd=$null;telemetryConsistent=$false};$state=[ordered]@{status='WAITING_PROVIDER';stage='REVIEW';taskId='PB1-P01-os-state-machine';taskVersionId=$tv;runId=$run;candidateHead=('c'*40);providerHistory=@($history)}
            $budget=[ordered]@{schemaVersion='orcivo.orchestration.v2.deepseek-budget/1';month=(Get-Date).ToUniversalTime().ToString('yyyy-MM');spentUsd=0;invocations=@([ordered]@{invocationId=$inv;model='deepseek-v4-flash';costUsd=$null;telemetryStatus='UNKNOWN';resultClass='AGENT_FAILURE';exitCode=1});reservations=@([ordered]@{invocationId=$inv;model='deepseek-v4-flash';maxUsd=0.03;status='ACTIVE'})};$budgetPath=Get-DeepSeekBudgetPath;Write-TestJson $budgetPath $budget
            Initialize-LedgerTask -TaskVersionId $tv -Identity @{taskId='DS22'}|Out-Null;Add-LedgerEvent -TaskVersionId $tv -Event ready -ToState READY -RunId $run|Out-Null;Add-LedgerEvent -TaskVersionId $tv -Event dispatch -ToState DISPATCHED -RunId $run -AttemptId $inv|Out-Null;Add-LedgerEvent -TaskVersionId $tv -Event running -ToState RUNNING -RunId $run|Out-Null;Add-LedgerEvent -TaskVersionId $tv -Event provider-unavailable -ToState WAITING_PROVIDER -RunId $run|Out-Null
            $proofArgs=@{State=$state;TaskId='PB1-P01-os-state-machine';TaskVersionId=$tv;RunId=$run;InvocationId=$inv;ExpectedRequestManifestHash=[string]$request.manifestHash;ExpectedResultReceiptHash=[string]$receipt.receiptHash;ExpectedStdoutHash=$stdoutHash;ExpectedStderrHash=$stderrHash;ExpectedTailSeq=5;BudgetPath=$budgetPath;V2Root=$localV2}
            $wrong=@{}+$proofArgs;$wrong.InvocationId='att-'+('6'*32);Assert-True (-not(Test-DispatcherDeepSeekUnknownActiveReservation @wrong).eligible) 'wrong invocation was accepted'
            $wrong=@{}+$proofArgs;$wrong.RunId='run-wrong';Assert-True (-not(Test-DispatcherDeepSeekUnknownActiveReservation @wrong).eligible) 'wrong run was accepted'
            $wrong=@{}+$proofArgs;$wrong.TaskId='PB1-WRONG';Assert-True (-not(Test-DispatcherDeepSeekUnknownActiveReservation @wrong).eligible) 'wrong task was accepted'
            $wrong=@{}+$proofArgs;$wrong.TaskVersionId=('d'*64);Assert-True (-not(Test-DispatcherDeepSeekUnknownActiveReservation @wrong).eligible) 'wrong task version was accepted'
            $wrong=@{}+$proofArgs;$wrong.ExpectedResultReceiptHash=('sha256:'+('0'*64));Assert-True (-not(Test-DispatcherDeepSeekUnknownActiveReservation @wrong).eligible) 'missing or ambiguous result receipt evidence was accepted'
            $setEvidence={param([string]$content)[IO.File]::WriteAllText($stdout,$content,(New-Object Text.UTF8Encoding($false)));$hash=New-FileHash $stdout;$history.stdoutHash=$hash;$history.controlRecordHash=$hash;$receipt.stdoutHash=$hash;$receipt.controlRecordHash=$hash;$signed=[ordered]@{};foreach($k in $receipt.Keys){if($k -ne 'receiptHash'){$signed[$k]=$receipt[$k]}};$receipt.receiptHash=New-ContentHash $signed;Write-TestJson $receiptPath $receipt;$case=@{}+$proofArgs;$case.ExpectedStdoutHash=$hash;$case.ExpectedResultReceiptHash=[string]$receipt.receiptHash;return $case}
            $arbitrary='{"type":"error","message":"{\"error\":{\"message\":\"Invalid parameter: temperature\",\"type\":\"invalid_request_error\"}}"}'+"`n"+'{"type":"turn.failed","error":{"message":"{\"error\":{\"message\":\"Invalid parameter: temperature\",\"type\":\"invalid_request_error\"}}"}}'+"`n";$case=&$setEvidence $arbitrary;Assert-True (-not(Test-DispatcherDeepSeekUnknownActiveReservation @case).eligible) 'arbitrary invalid_request_error was reconciliation-eligible'
            $auth='{"type":"error","message":"{\"error\":{\"message\":\"Authentication failed\",\"type\":\"authentication_error\"}}"}'+"`n"+'{"type":"turn.failed","error":{"message":"{\"error\":{\"message\":\"Authentication failed\",\"type\":\"authentication_error\"}}"}}'+"`n";$case=&$setEvidence $auth;Assert-True (-not(Test-DispatcherDeepSeekUnknownActiveReservation @case).eligible) 'authentication failure was reconciliation-eligible'
            $rate='{"type":"error","message":"{\"error\":{\"message\":\"Rate limit exceeded\",\"type\":\"rate_limit_error\"}}"}'+"`n"+'{"type":"turn.failed","error":{"message":"{\"error\":{\"message\":\"Rate limit exceeded\",\"type\":\"rate_limit_error\"}}"}}'+"`n";$case=&$setEvidence $rate;Assert-True (-not(Test-DispatcherDeepSeekUnknownActiveReservation @case).eligible) 'rate limit failure was reconciliation-eligible'
            $ambiguous=$raw+'{"type":"turn.failed","error":{"message":"{\"error\":{\"message\":\"Invalid json schema: duplicate failure evidence\",\"type\":\"invalid_request_error\"}}"}}'+"`n";$case=&$setEvidence $ambiguous;Assert-True (-not(Test-DispatcherDeepSeekUnknownActiveReservation @case).eligible) 'ambiguous duplicate turn.failed evidence was reconciliation-eligible'
            $missing='{"type":"error","message":"{\"error\":{\"message\":\"Invalid json schema: missing terminal evidence\",\"type\":\"invalid_request_error\"}}"}'+"`n";$case=&$setEvidence $missing;Assert-True (-not(Test-DispatcherDeepSeekUnknownActiveReservation @case).eligible) 'missing turn.failed evidence was reconciliation-eligible'
            $proofArgs=&$setEvidence $raw
            [IO.File]::AppendAllText($stdout,'tampered',(New-Object Text.UTF8Encoding($false)));Assert-True (-not(Test-DispatcherDeepSeekUnknownActiveReservation @proofArgs).eligible) 'stdout hash tampering was accepted';[IO.File]::WriteAllText($stdout,$raw,(New-Object Text.UTF8Encoding($false)))
            $mismatch=Read-V2Json $budgetPath;$mismatch.reservations[0].maxUsd=0.04;Write-TestJson $budgetPath $mismatch;Assert-True (-not(Test-DispatcherDeepSeekUnknownActiveReservation @proofArgs).eligible) 'mismatched active reservation was accepted';Write-TestJson $budgetPath $budget
            $conflict=Read-V2Json $budgetPath;$conflict.invocations[0].costUsd=0.01;Write-TestJson $budgetPath $conflict;Assert-True (-not(Test-DispatcherDeepSeekUnknownActiveReservation @proofArgs).eligible) 'conflicting pre-existing cost was accepted';Write-TestJson $budgetPath $budget
            $eligible=Test-DispatcherDeepSeekUnknownActiveReservation @proofArgs;Assert-True ($eligible.eligible -and [decimal]$eligible.reservation.maxUsd -eq 0.03) "exact unknown review reservation was not eligible: $($eligible.reason)"
            $historyBefore=ConvertTo-CanonicalJson $state.providerHistory;$first=Reconcile-DispatcherDeepSeekUnknownActiveReservation @proofArgs;$second=Reconcile-DispatcherDeepSeekUnknownActiveReservation @proofArgs;$after=Read-V2Json $budgetPath;$status=Get-DeepSeekBudgetStatus;$events=@((Read-JsonLines (Get-LedgerPath $tv))|Where-Object event -eq 'deepseek-unknown-reservation-reconciled')
            Assert-True ($first.status -eq 'RECONCILED_RESERVATION_CEILING' -and $second.status -eq 'ALREADY_RECONCILED' -and [decimal]$after.spentUsd -eq 0.03 -and [decimal]$after.invocations[0].costUsd -eq 0.03 -and $after.invocations[0].telemetryStatus -eq 'RECONCILED' -and $after.invocations[0].costAccuracy -eq 'RESERVATION_CEILING' -and $after.invocations[0].billingObservation -eq 'EXACT_PROVIDER_BILLING_UNOBSERVED' -and $after.reservations[0].status -eq 'RELEASED' -and $events.Count -eq 1 -and $status.ok -and (ConvertTo-CanonicalJson $state.providerHistory) -eq $historyBefore) "ceiling reconciliation mismatch first=$($first.status) second=$($second.status) spent=$($after.spentUsd) invocations=$(@($after.invocations).Count) cost=$($after.invocations[0].costUsd) telemetry=$($after.invocations[0].telemetryStatus) accuracy=$($after.invocations[0].costAccuracy) billing=$($after.invocations[0].billingObservation) reservation=$($after.reservations[0].status) events=$($events.Count) healthy=$($status.ok) history=$((ConvertTo-CanonicalJson $state.providerHistory) -eq $historyBefore) reason=$($status.reason) path=$($status.path) expected=$budgetPath"
            $reconciliationReceipt=Join-Path $localV2 "runs\$run\reconciliations\deepseek-$inv.unknown-reservation.json";[IO.File]::AppendAllText($reconciliationReceipt,'tampered',(New-Object Text.UTF8Encoding($false)));Assert-True (-not(Test-DispatcherDeepSeekUnknownActiveReservation @proofArgs).eligible) 'tampered reconciliation receipt was accepted'
        }finally{$script:V2Dir=$oldV2;$script:V2Config=$oldCfg;$script:LedgerDir=$oldLedger;$script:DeepSeekBudgetDir=$oldBudget;$script:DispatcherRecoveryRunnerProbe=$oldProbe}
    }
    Check 'DS-18' {
        $oldV2=$script:V2Dir;$oldCfg=$script:V2Config;$oldLedger=$script:LedgerDir;$oldRuntime=$script:DeepSeekRuntimePath;$oldBudget=$script:DeepSeekBudgetDir;$oldRegistry=$script:DeepSeekPriceRegistryPath;$oldProbe=$script:DispatcherRecoveryRunnerProbe
        try{
            $tv=('a'*64);$run='run-ds18-fixture';$inv=('att-'+('4'*32));$localV2=Join-Path $root 'v2';New-Item -ItemType Directory -Force -Path $localV2|Out-Null;Copy-Item (Join-Path (Get-RepoRoot) '.orchestration\v2\config.v2.json') (Join-Path $localV2 'config.v2.json')
            $script:V2Dir=$localV2;$script:V2Config=Join-Path $localV2 'config.v2.json';$script:LedgerDir=Join-Path $localV2 'ledger';$script:DeepSeekRuntimePath=$runtime;$script:DeepSeekBudgetDir=Join-Path $localV2 'budgets';$script:DeepSeekPriceRegistryPath=$registry;$script:DispatcherRecoveryRunnerProbe=$false
            $logs=Join-Path $localV2 "runs\$run\logs";New-Item -ItemType Directory -Force -Path $logs|Out-Null;$prompt=Join-Path $logs 'implementer-347-deepseek-44444444.prompt.txt';Write-TestJson $prompt 'prompt';$promptHash=New-FileHash $prompt;$request=New-DeepSeekRequestManifest -InvocationId $inv -PromptHash $promptHash -Model deepseek-v4-pro -Reasoning high -Profile REASONING;$requestPath=Join-Path $logs 'implementer-347-deepseek-44444444.request-manifest.json';Write-TestJson $requestPath $request;$stdout=Join-Path $logs 'implementer-347-deepseek-44444444.stdout.log';[IO.File]::WriteAllText($stdout,'{"type":"response.completed","response":{"usage":{"input_tokens":10,"output_tokens":2}}}' + "`n",(New-Object Text.UTF8Encoding($false)));$stdoutHash=New-FileHash $stdout
            $pre=[ordered]@{invocationId=$inv;attempt=347;provider='deepseek';model='deepseek-v4-pro';promptArtifact=$prompt;promptHash=$promptHash;snapshotHash='sha256:pre'};$post=[ordered]@{invocationId=$inv;attempt=347;preInvocationSnapshotHash='sha256:pre';stdoutHash=$stdoutHash;resultHash='sha256:post'};$state=[ordered]@{status='WAITING_PROVIDER';stage='IMPLEMENT';runId=$run;taskVersionId=$tv;providerHistory=@([ordered]@{invocationId=$inv;attempt=347;provider='deepseek';model='deepseek-v4-pro';exitCode=0;stdoutArtifact=$stdout;stdoutHash=$stdoutHash});workspaceInvocationSnapshots=@($pre);workspaceInvocationResultSnapshots=@($post);quarantineRetryRoute=[ordered]@{policy='CLEAN_QUARANTINED_RETRY_REQUIRES_FRESH_DEEPSEEK_PRO_HIGH';provider='deepseek';model='deepseek-v4-pro';profile='REASONING';reasoning='high'}}
            $budget=[ordered]@{schemaVersion='orcivo.orchestration.v2.deepseek-budget/1';month=(Get-Date).ToUniversalTime().ToString('yyyy-MM');spentUsd=0;invocations=@([ordered]@{invocationId=$inv;model='deepseek-v4-pro';costUsd=$null;telemetryStatus='UNKNOWN'});reservations=@([ordered]@{invocationId=$inv;model='deepseek-v4-pro';maxUsd=0.20;status='ACTIVE'})};$fixtureBudgetPath=Join-Path $localV2 'budgets\deepseek-fixture.json';Write-TestJson $fixtureBudgetPath $budget
            $fixtureBudget=Read-V2Json $fixtureBudgetPath;Assert-True (@($fixtureBudget.invocations|Where-Object{[string]$_.invocationId -eq $inv}).Count -eq 1) 'DS18 fixture invocation binding is absent';Assert-True (@($fixtureBudget.reservations|Where-Object{[string]$_.invocationId -eq $inv}).Count -eq 1) 'DS18 fixture reservation binding is absent'
            Initialize-LedgerTask -TaskVersionId $tv -Identity @{taskId='DS18'}|Out-Null;Add-LedgerEvent -TaskVersionId $tv -Event ready -ToState READY -RunId $run|Out-Null;Add-LedgerEvent -TaskVersionId $tv -Event 'provider-unavailable' -ToState WAITING_PROVIDER -RunId $run|Out-Null
            try{Reconcile-DispatcherDeepSeekUnknownReservation -State $state -TaskVersionId $tv -RunId $run -InvocationId $inv -ExpectedRequestManifestHash ('sha256:'+('0'*64)) -ExpectedStdoutHash $stdoutHash -ExpectedTailSeq 3 -BudgetPath $fixtureBudgetPath -V2Root $localV2;throw 'wrong request hash accepted'}catch{Assert-True ($_.Exception.Message -match 'hash') 'wrong request hash did not fail closed'}
            try{Reconcile-DispatcherDeepSeekUnknownReservation -State $state -TaskVersionId $tv -RunId $run -InvocationId $inv -ExpectedRequestManifestHash $request.manifestHash -ExpectedStdoutHash $stdoutHash -ExpectedTailSeq 4 -BudgetPath $fixtureBudgetPath -V2Root $localV2;throw 'wrong ledger tail accepted'}catch{Assert-True ($_.Exception.Message -match 'ledger tail') 'wrong ledger tail did not fail closed'}
            $first=Reconcile-DispatcherDeepSeekUnknownReservation -State $state -TaskVersionId $tv -RunId $run -InvocationId $inv -ExpectedRequestManifestHash $request.manifestHash -ExpectedStdoutHash $stdoutHash -ExpectedTailSeq 3 -BudgetPath $fixtureBudgetPath -V2Root $localV2;$second=Reconcile-DispatcherDeepSeekUnknownReservation -State $state -TaskVersionId $tv -RunId $run -InvocationId $inv -ExpectedRequestManifestHash $request.manifestHash -ExpectedStdoutHash $stdoutHash -ExpectedTailSeq 3 -BudgetPath $fixtureBudgetPath -V2Root $localV2;$after=Read-V2Json $fixtureBudgetPath;Assert-True ($first.status -eq 'RECONCILED_RESERVATION_CEILING' -and $second.status -eq 'ALREADY_RECONCILED' -and [decimal]$after.spentUsd -eq 0.20 -and [string]$after.reservations[0].status -eq 'RELEASED' -and (Get-LedgerState $tv).state -eq 'WAITING_PROVIDER') 'reservation ceiling reconciliation was not durable and idempotent'
            $receipt=Join-Path $localV2 "runs\$run\reconciliations\deepseek-$inv.reservation-ceiling.json";Add-Content -LiteralPath $receipt -Value 'tampered';try{Reconcile-DispatcherDeepSeekUnknownReservation -State $state -TaskVersionId $tv -RunId $run -InvocationId $inv -ExpectedRequestManifestHash $request.manifestHash -ExpectedStdoutHash $stdoutHash -ExpectedTailSeq 3 -BudgetPath $fixtureBudgetPath -V2Root $localV2;throw 'tampered receipt accepted'}catch{Assert-True ($_.Exception.Message -match 'receipt') 'tampered receipt did not fail closed'}
        }finally{$script:V2Dir=$oldV2;$script:V2Config=$oldCfg;$script:LedgerDir=$oldLedger;$script:DeepSeekRuntimePath=$oldRuntime;$script:DeepSeekBudgetDir=$oldBudget;$script:DeepSeekPriceRegistryPath=$oldRegistry;$script:DispatcherRecoveryRunnerProbe=$oldProbe}
    }
}finally{
    $results|ForEach-Object{Write-Output $_}
    $fails=@($results|Where-Object{$_ -match ' FAIL:'});Write-Output ("DEEPSEEK_TESTS: "+$(if($fails.Count){'FAIL'}else{'PASS'})+" ($($results.Count-$fails.Count)/$($results.Count) PASS)")
    if(Test-Path -LiteralPath $root){Remove-Item -LiteralPath $root -Recurse -Force}
}
if(@($results|Where-Object{$_ -match ' FAIL:'}).Count){exit 1}
