export enum PlanFeature {
  PDF_WATERMARK = 'PDF_WATERMARK',
  PHOTOS_IN_OS = 'PHOTOS_IN_OS',
  MAX_CUSTOMERS = 'MAX_CUSTOMERS',
  MAX_QUOTES_PER_MONTH = 'MAX_QUOTES_PER_MONTH',
  MAX_WORK_ORDERS_PER_MONTH = 'MAX_WORK_ORDERS_PER_MONTH',
}
